CREATE CACHED TABLE  USER_ACCOUNTS (
	RECORD_ID BIGINT IDENTITY (100,1),
	USER_ROLE VARCHAR(255) NULL,
	USER_ID VARCHAR(255) NULL,
	USER_PWD VARCHAR(255) NULL,
	AUTH_TOKEN VARCHAR(255) NULL,
	EMAIL_ONE	 VARCHAR(255) NULL ,
	EMAIL_TWO	VARCHAR(255) NULL ,
	FNAME	VARCHAR(255) NULL ,
	LNAME	VARCHAR(255) NULL ,
	STATUS VARCHAR(255) NULL,
	COUNTRY_ID	VARCHAR(2) NULL ,
	COMPANY_NAME	VARCHAR(255) NULL,
	WHEN_CHANGED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	WHEN_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(USER_ID)
);

-- :

create index idx1 on user_accounts (email_one);

-- :

create index idx2 on user_accounts (company_name);

-- :

create index idx3 on user_accounts (email_two);

-- :

create index idx4 on user_accounts (user_role);


